<?php
/**
 * WeCodeArt Framework.
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package 	WeCodeArt Framework
 * @subpackage 	Support\Modules\SmoothScroll
 * @copyright   Copyright (c) 2025, WeCodeArt Framework
 * @since 		6.7.0
 * @version		6.7.0
 */

namespace WeCodeArt\Support\Modules;

defined( 'ABSPATH' ) || exit;

use WeCodeArt\{ Singleton, Integration };
use WeCodeArt\Config\Traits\{ Asset, No_Conditionals };
use function WeCodeArt\Functions\{ get_prop, toJSON };

/**
 * The SmoothScroll object.
 */
final class SmoothScroll implements Integration {

    use Asset;
    use Singleton;
	use No_Conditionals;

	const CONTEXT = 'wca-smoothscroll';

    /**
	 * The config of the plugin.
	 *
	 * @since    1.0.0
	 * @access   protected
	 * @var      mixed    $config    The config of the plugin.
	 */
	protected $config;

	/**
	 * Send to Constructor
	 */
	public function init() {
        $this->config = wp_parse_args( wecodeart_option( 'smoothscroll' ), self::get_defaults() );
	}

	/**
	 * Hooks
	 */
	public function register_hooks() {
		\add_action( 'init',					[ $this, 'front_assets' ] );
		\add_action( 'admin_enqueue_scripts',	[ $this, 'admin_assets' ] );
		\add_action( 'admin_init',				[ $this, 'insert_defaults'	] );
	}

	/**
	 * Assets
	 *
	 * @return 	void
	 */
	public function front_assets(): void {
		\wecodeart( 'assets' )->add_script( $this->make_handle(), [
			'path' 		=> $this->get_asset( 'js', 'front' ),
			'load'		=> function() {
				$exclude = get_prop( $this->config, 'excludeIds', '' );
				$load 	 = true;
				
				if( empty( $exclude ) ) {
					return $load;
				}
				
				$ids 	= array_map( 'intval', array_map( 'trim', explode( ',', $exclude ) ) );
				$load 	= ! in_array( get_queried_object_id(), $ids );

				return $load;
			},
			'locale'	=> [
				// Scrolling Core
				'frameRate' 	=> intval( get_prop( $this->config, 'frameRate', 150 ) ),
				'animationTime' => intval( get_prop( $this->config, 'animationTime', 1000 ) ),
				'stepSize' 		=> intval( get_prop( $this->config, 'stepSize', 100 ) ),
				
				// Pulse
				'pulseAlgorithm' => get_prop( $this->config, 'pulseAlgorithm', true ),
				'pulseScale'	 => intval( get_prop( $this->config, 'pulseScale', 4 ) ),
				'pulseNormalize' => intval( get_prop( $this->config, 'pulseNormalize', 1 ) ),
				
				// Acceleration
				'accelerationDelta' => intval( get_prop( $this->config, 'accelerationDelta', 50 ) ),
				'accelerationMax' 	=> intval( get_prop( $this->config, 'accelerationMax', 3 ) ),
				
				// Keyboard Settings
				'keyboardSupport'   => get_prop( $this->config, 'keyboardSupport', true ),
				'arrowScroll' 		=> intval( get_prop( $this->config, 'arrowScroll', 50 ) ),
				
				// Custom settings
				'behavior' 	=> get_prop( $this->config, 'behavior', 'smooth' ),
				'offset' 	=> intval( get_prop( $this->config, 'offset', 0 ) ),

				// Exclude
				'excludeIds' => get_prop( $this->config, 'excludeIds', '' ),
			],
		] );
	}

	/**
	 * Admin Assets
	 *
	 * @return 	void
	 */
	public function admin_assets(): void {
		if( ! wecodeart_if( 'is_theme_admin' ) || ! current_user_can( 'activate_plugins' ) ) {
			return;
		}

		\wp_register_script( 
			$this->make_handle( 'admin' ),
			$this->get_asset( 'js', 'admin' ),
			[ 'wecodeart-admin', 'wp-block-editor' ],
			wecodeart( 'version' ),
			true 
		);

		\wp_enqueue_script( $this->make_handle( 'admin' ) );

		\wp_set_script_translations( $this->make_handle( 'admin' ), 'wecodeart', wecodeart_config( 'directories' )['languages'] );
	}

	/**
	 * Get asset path
	 *
	 * @param 	string 	$type
	 * @param 	string 	$name
	 *
	 * @return 	string
	 */
	public function get_asset( string $type, string $name ): string {
		$file_path = wecodeart_if( 'is_dev_mode' ) ? 'unminified' : 'minified';
		$file_name = wecodeart_if( 'is_dev_mode' ) ? $name . '.' . $type :  $name . '.min.' . $type;
		$file_path = wecodeart_config( 'paths' )['uri'] . '/inc/support/modules/smoothscroll/assets/' . $file_path . '/' . $type . '/' . $file_name;

		return esc_url( $file_path );
	}

	/**
	 * Insert defaults
	 *
	 * @return 	void
	 */
	public function insert_defaults(): void {
		$options = wecodeart_option( 'smoothscroll' );
		
		if( empty( $options ) ) {
			wecodeart_option( [
				'smoothscroll' => self::get_defaults()
			] );
		}
	}

	/**
	 * Get defaults
	 *
	 * @return 	array
	 */
	public static function get_defaults(): array {
		return [
			// Scrolling Core
			'frameRate'     => 150,
			'animationTime' => 1000,
			'stepSize'      => 100,
			
			// Pulse
			'pulseAlgorithm' => true,
			'pulseScale'     => 4,
			'pulseNormalize' => 1,
			
			// Acceleration
			'accelerationDelta' => 50,
			'accelerationMax'   => 3,
			
			// Keyboard Settings
			'keyboardSupport' 	=> true,
			'arrowScroll' 		=> 50,

			// Exclude
			'excludeIds' => '',
		];
	}
} 